# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Dennis/Vivado/HDMI_3/HDMI_3.srcs/sources_1/bd/design_2/ip/design_2_rgb2dvi_0_0/design_2_rgb2dvi_0_0.xci
# IP: The module: 'design_2_rgb2dvi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dennis/Vivado/HDMI_3/HDMI_3.srcs/sources_1/bd/design_2/ip/design_2_rgb2dvi_0_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dennis/Vivado/HDMI_3/HDMI_3.srcs/sources_1/bd/design_2/ip/design_2_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dennis/Vivado/HDMI_3/HDMI_3.srcs/sources_1/bd/design_2/ip/design_2_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Dennis/Vivado/HDMI_3/HDMI_3.srcs/sources_1/bd/design_2/ip/design_2_rgb2dvi_0_0/design_2_rgb2dvi_0_0.xci
# IP: The module: 'design_2_rgb2dvi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dennis/Vivado/HDMI_3/HDMI_3.srcs/sources_1/bd/design_2/ip/design_2_rgb2dvi_0_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dennis/Vivado/HDMI_3/HDMI_3.srcs/sources_1/bd/design_2/ip/design_2_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Dennis/Vivado/HDMI_3/HDMI_3.srcs/sources_1/bd/design_2/ip/design_2_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_rgb2dvi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
