# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# Block Designs: bd/design_3/design_3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3 || ORIG_REF_NAME==design_3} -quiet] -quiet

# IP: bd/design_3/ip/design_3_HDMI_HPD_0/design_3_HDMI_HPD_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_HDMI_HPD_0 || ORIG_REF_NAME==design_3_HDMI_HPD_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_clk_wiz_0_0/design_3_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_clk_wiz_0_0 || ORIG_REF_NAME==design_3_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_dvi2rgb_0_0/design_3_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_dvi2rgb_0_0 || ORIG_REF_NAME==design_3_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_rgb2dvi_0_0/design_3_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_rgb2dvi_0_0 || ORIG_REF_NAME==design_3_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_v_axi4s_vid_out_0_0/design_3_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==design_3_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_v_tc_0_0/design_3_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_v_tc_0_0 || ORIG_REF_NAME==design_3_v_tc_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_v_vid_in_axi4s_0_0/design_3_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==design_3_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_xlconstant_0_0/design_3_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_xlconstant_0_0 || ORIG_REF_NAME==design_3_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_3/ip/design_3_sobel_0_0/design_3_sobel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_3_sobel_0_0 || ORIG_REF_NAME==design_3_sobel_0_0} -quiet] -quiet

# XDC: bd/design_3/design_3_ooc.xdc
