# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Dennis/Vivado/HDMI_3/HDMI_3.srcs/sources_1/bd/design_3/ip/design_3_sobel_0_0/design_3_sobel_0_0.xci
# IP: The module: 'design_3_sobel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dennis/Vivado/HDMI_3/HDMI_3.srcs/sources_1/bd/design_3/ip/design_3_sobel_0_0/constraints/sobel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_sobel_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Dennis/Vivado/HDMI_3/HDMI_3.srcs/sources_1/bd/design_3/ip/design_3_sobel_0_0/design_3_sobel_0_0.xci
# IP: The module: 'design_3_sobel_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dennis/Vivado/HDMI_3/HDMI_3.srcs/sources_1/bd/design_3/ip/design_3_sobel_0_0/constraints/sobel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_3_sobel_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
