// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module CvtColor (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        p_src_rows_V_dout,
        p_src_rows_V_empty_n,
        p_src_rows_V_read,
        p_src_cols_V_dout,
        p_src_cols_V_empty_n,
        p_src_cols_V_read,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state8 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [10:0] p_src_rows_V_dout;
input   p_src_rows_V_empty_n;
output   p_src_rows_V_read;
input  [11:0] p_src_cols_V_dout;
input   p_src_cols_V_empty_n;
output   p_src_cols_V_read;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg p_src_rows_V_read;
reg p_src_cols_V_read;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    p_src_rows_V_blk_n;
reg    p_src_cols_V_blk_n;
reg    p_src_data_stream_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln1968_reg_320;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] icmp_ln1968_reg_320_pp0_iter3_reg;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [10:0] j_0_i_reg_162;
reg   [11:0] p_src_cols_V_read_reg_301;
reg    ap_block_state1;
reg   [10:0] p_src_rows_V_read_reg_306;
wire   [0:0] icmp_ln1967_fu_177_p2;
wire    ap_CS_fsm_state2;
wire   [9:0] i_fu_182_p2;
reg   [9:0] i_reg_315;
wire   [0:0] icmp_ln1968_fu_192_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
reg    ap_block_state7_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln1968_reg_320_pp0_iter1_reg;
reg   [0:0] icmp_ln1968_reg_320_pp0_iter2_reg;
wire   [10:0] j_fu_197_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [7:0] tmp_51_reg_329;
reg   [7:0] tmp_52_reg_334;
reg   [7:0] tmp_52_reg_334_pp0_iter2_reg;
reg   [7:0] tmp_53_reg_339;
reg   [7:0] tmp_53_reg_339_pp0_iter2_reg;
wire   [28:0] mul_ln703_fu_277_p2;
reg   [28:0] mul_ln703_reg_344;
wire   [29:0] grp_fu_283_p3;
reg   [29:0] ret_V_1_reg_349;
reg    ap_enable_reg_pp0_iter3;
reg   [7:0] p_Val2_14_reg_354;
reg   [0:0] tmp_reg_359;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter2;
reg   [9:0] i_0_i_reg_151;
wire    ap_CS_fsm_state8;
wire   [7:0] p_Val2_s_fu_266_p3;
reg    ap_block_pp0_stage0_01001;
wire   [10:0] zext_ln1967_fu_173_p1;
wire   [11:0] zext_ln1968_fu_188_p1;
wire   [28:0] grp_fu_293_p3;
wire   [7:0] zext_ln415_fu_231_p1;
wire   [0:0] tmp_48_fu_239_p3;
wire   [7:0] p_Val2_15_fu_234_p2;
wire   [0:0] tmp_49_fu_252_p3;
wire   [0:0] xor_ln777_fu_246_p2;
wire   [0:0] deleted_zeros_fu_260_p2;
wire   [21:0] mul_ln703_fu_277_p0;
wire   [7:0] mul_ln703_fu_277_p1;
wire   [22:0] grp_fu_283_p0;
wire   [7:0] grp_fu_283_p1;
wire   [28:0] grp_fu_283_p2;
wire   [19:0] grp_fu_293_p0;
wire   [7:0] grp_fu_293_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [29:0] grp_fu_283_p10;
wire   [29:0] grp_fu_283_p20;
wire   [27:0] grp_fu_293_p10;
wire   [28:0] mul_ln703_fu_277_p10;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

sobel_mul_mul_22nbkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 22 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 29 ))
sobel_mul_mul_22nbkb_U18(
    .din0(mul_ln703_fu_277_p0),
    .din1(mul_ln703_fu_277_p1),
    .dout(mul_ln703_fu_277_p2)
);

sobel_mac_muladd_cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 30 ))
sobel_mac_muladd_cud_U19(
    .din0(grp_fu_283_p0),
    .din1(grp_fu_283_p1),
    .din2(grp_fu_283_p2),
    .dout(grp_fu_283_p3)
);

sobel_mac_muladd_dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
sobel_mac_muladd_dEe_U20(
    .din0(grp_fu_293_p0),
    .din1(grp_fu_293_p1),
    .din2(mul_ln703_reg_344),
    .dout(grp_fu_293_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1967_fu_177_p2 == 1'd0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((icmp_ln1967_fu_177_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if (((icmp_ln1967_fu_177_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        i_0_i_reg_151 <= i_reg_315;
    end else if ((~((p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_i_reg_151 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1968_fu_192_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        j_0_i_reg_162 <= j_fu_197_p2;
    end else if (((icmp_ln1967_fu_177_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        j_0_i_reg_162 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_315 <= i_fu_182_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln1968_reg_320 <= icmp_ln1968_fu_192_p2;
        icmp_ln1968_reg_320_pp0_iter1_reg <= icmp_ln1968_reg_320;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln1968_reg_320_pp0_iter2_reg <= icmp_ln1968_reg_320_pp0_iter1_reg;
        icmp_ln1968_reg_320_pp0_iter3_reg <= icmp_ln1968_reg_320_pp0_iter2_reg;
        tmp_52_reg_334_pp0_iter2_reg <= tmp_52_reg_334;
        tmp_53_reg_339_pp0_iter2_reg <= tmp_53_reg_339;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1968_reg_320_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        mul_ln703_reg_344 <= mul_ln703_fu_277_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1968_reg_320_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_14_reg_354 <= {{grp_fu_283_p3[29:22]}};
        tmp_reg_359 <= grp_fu_283_p3[32'd21];
    end
end

always @ (posedge ap_clk) begin
    if ((~((p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_cols_V_read_reg_301 <= p_src_cols_V_dout;
        p_src_rows_V_read_reg_306 <= p_src_rows_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1968_reg_320_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ret_V_1_reg_349 <= grp_fu_283_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1968_reg_320 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_51_reg_329 <= p_src_data_stream_0_V_dout;
        tmp_52_reg_334 <= p_src_data_stream_1_V_dout;
        tmp_53_reg_339 <= p_src_data_stream_2_V_dout;
    end
end

always @ (*) begin
    if ((icmp_ln1968_fu_192_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1967_fu_177_p2 == 1'd0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1967_fu_177_p2 == 1'd0))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_cols_V_blk_n = p_src_cols_V_empty_n;
    end else begin
        p_src_cols_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_cols_V_read = 1'b1;
    end else begin
        p_src_cols_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1968_reg_320 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln1968_reg_320 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1968_reg_320 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln1968_reg_320 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1968_reg_320 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln1968_reg_320 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_rows_V_blk_n = p_src_rows_V_empty_n;
    end else begin
        p_src_rows_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_rows_V_read = 1'b1;
    end else begin
        p_src_rows_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln1967_fu_177_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln1968_fu_192_p2 == 1'd0)) & ~((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln1968_fu_192_p2 == 1'd0)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln1968_reg_320 == 1'd1) & (p_src_data_stream_2_V_empty_n == 1'b0)) | ((icmp_ln1968_reg_320 == 1'd1) & (p_src_data_stream_1_V_empty_n == 1'b0)) | ((icmp_ln1968_reg_320 == 1'd1) & (p_src_data_stream_0_V_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln1968_reg_320 == 1'd1) & (p_src_data_stream_2_V_empty_n == 1'b0)) | ((icmp_ln1968_reg_320 == 1'd1) & (p_src_data_stream_1_V_empty_n == 1'b0)) | ((icmp_ln1968_reg_320 == 1'd1) & (p_src_data_stream_0_V_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter1 == 1'b1) & (((icmp_ln1968_reg_320 == 1'd1) & (p_src_data_stream_2_V_empty_n == 1'b0)) | ((icmp_ln1968_reg_320 == 1'd1) & (p_src_data_stream_1_V_empty_n == 1'b0)) | ((icmp_ln1968_reg_320 == 1'd1) & (p_src_data_stream_0_V_empty_n == 1'b0)))) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((p_src_cols_V_empty_n == 1'b0) | (p_src_rows_V_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((icmp_ln1968_reg_320 == 1'd1) & (p_src_data_stream_2_V_empty_n == 1'b0)) | ((icmp_ln1968_reg_320 == 1'd1) & (p_src_data_stream_1_V_empty_n == 1'b0)) | ((icmp_ln1968_reg_320 == 1'd1) & (p_src_data_stream_0_V_empty_n == 1'b0)));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter4 = (((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((icmp_ln1968_reg_320_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign deleted_zeros_fu_260_p2 = (xor_ln777_fu_246_p2 | tmp_49_fu_252_p3);

assign grp_fu_283_p0 = 30'd2462056;

assign grp_fu_283_p1 = grp_fu_283_p10;

assign grp_fu_283_p10 = tmp_52_reg_334_pp0_iter2_reg;

assign grp_fu_283_p2 = grp_fu_283_p20;

assign grp_fu_283_p20 = grp_fu_293_p3;

assign grp_fu_293_p0 = 28'd478150;

assign grp_fu_293_p1 = grp_fu_293_p10;

assign grp_fu_293_p10 = tmp_53_reg_339_pp0_iter2_reg;

assign i_fu_182_p2 = (i_0_i_reg_151 + 10'd1);

assign icmp_ln1967_fu_177_p2 = (($signed(zext_ln1967_fu_173_p1) < $signed(p_src_rows_V_read_reg_306)) ? 1'b1 : 1'b0);

assign icmp_ln1968_fu_192_p2 = (($signed(zext_ln1968_fu_188_p1) < $signed(p_src_cols_V_read_reg_301)) ? 1'b1 : 1'b0);

assign j_fu_197_p2 = (j_0_i_reg_162 + 11'd1);

assign mul_ln703_fu_277_p0 = 29'd1254096;

assign mul_ln703_fu_277_p1 = mul_ln703_fu_277_p10;

assign mul_ln703_fu_277_p10 = tmp_51_reg_329;

assign p_Val2_15_fu_234_p2 = (zext_ln415_fu_231_p1 + p_Val2_14_reg_354);

assign p_Val2_s_fu_266_p3 = ((deleted_zeros_fu_260_p2[0:0] === 1'b1) ? p_Val2_15_fu_234_p2 : 8'd255);

assign p_dst_data_stream_0_V_din = p_Val2_s_fu_266_p3;

assign p_dst_data_stream_1_V_din = p_Val2_s_fu_266_p3;

assign p_dst_data_stream_2_V_din = p_Val2_s_fu_266_p3;

assign start_out = real_start;

assign tmp_48_fu_239_p3 = ret_V_1_reg_349[32'd29];

assign tmp_49_fu_252_p3 = p_Val2_15_fu_234_p2[32'd7];

assign xor_ln777_fu_246_p2 = (tmp_48_fu_239_p3 ^ 1'd1);

assign zext_ln1967_fu_173_p1 = i_0_i_reg_151;

assign zext_ln1968_fu_188_p1 = j_0_i_reg_162;

assign zext_ln415_fu_231_p1 = tmp_reg_359;

endmodule //CvtColor
